apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: tbs-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: samarsinghal/petclinic:f27903964ba8e31ad89c31379e300a35fe1632a3
        name: spring-petclinic
        ports:
        - containerPort: 8080