apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: tbs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: samarsinghal/petclinic:latest
        name: spring-petclinic
        ports:
        - containerPort: 8080
