apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: library/spring-petclinic:latest
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
        - containerPort: 8080
