apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: tbs-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: samarsinghal/spring-petclinic:c4efc1036954d57fcd391ab4053595b1adef65e1
        name: spring-petclinic
        ports:
        - containerPort: 8080
