apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      imagePullSecrets:
      - name: app-registry-credentials
      containers:
      - image: harbor.poc.add2cloud.com/library/spring-petclinic
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
        - containerPort: 8080
