apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:0f452aee294d20389097812b9209bf2128c396a32dbb1270ac36888dab3aaa93
  name: harbor.poc.add2cloud.com/library/spring-petclinic
