apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:704aebcbb985593aa6540ee0272b2dc0bd6704f7b97417e5eae59d41b0d0f566
  name: harbor.poc.add2cloud.com/library/spring-petclinic
