apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

commonAnnotations:
  revision: sam
  revision-0c1ffc292fec5764512dc8d9a20285eb6b1a5380: 0c1ffc292fec5764512dc8d9a20285eb6b1a5380
