apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:fa736ad0088ca61faac829d3b3fc61ffdeb4e772ca87fdce4d16978fc91df3c6
  name: harbor.poc.add2cloud.com/library/spring-petclinic
