apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:17bdfcc5c521e731253fd436586d2680bea080ac73b10eacd5f318bec2de1664
  name: harbor.poc.add2cloud.com/library/spring-petclinic
