apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:e2cbe7b6b6a7ab5a95d33443e9e40111d59e15a8a8966707df68d608fd1ca2d6
  name: harbor.poc.add2cloud.com/library/spring-petclinic
