apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:8798d91b8d11c480279d794bbb9a6e4265c53d50264aa93d477cfa994c831dd8
  name: harbor.poc.add2cloud.com/library/spring-petclinic
