apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:371eb3f5507ecc36d76e810f166742ca1a3538b81198ddfd28fccc1aa670df5a
  name: harbor.poc.add2cloud.com/library/spring-petclinic
