apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:b28339198589b9606e91e9659eaeb49b0855ab1cc7678c1d8d19bd4f15fa5688
  name: harbor.poc.add2cloud.com/library/spring-petclinic
