apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:f54947bad9f07846596b6365f1a711678a0d910b7b7df9eed66041ad476d0751
  name: harbor.poc.add2cloud.com/library/spring-petclinic
