apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:debb8d52199901016335567149047a06d8fca0bd171521d578482ed7e6f520c5
  name: harbor.poc.add2cloud.com/library/spring-petclinic
