apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:dde4f5d9cb977624a608b745a2312913fa4359b094e4882f6e4ffe113e7e4094
  name: harbor.poc.add2cloud.com/library/spring-petclinic
