apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:b43b3d999352c67362b35dddb0ab9983ce7e60694488876464e408dd10d66130
  name: harbor.poc.add2cloud.com/library/spring-petclinic
