apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- name: harbor.poc.add2cloud.com/library/spring-petclinic
  newTag: sha256:394eae210a9e02a99ce1f77dd4349ac3a10738b6633ab0a84395c4ba5f12a289
