apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:1c54625998bf0a25a7b8c2d41bae52ec3a71c3383e26b69842ba5a8a486ce94c
  name: harbor.poc.add2cloud.com/library/spring-petclinic
