apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:09c4b9cc2061b401f2b5b9fe630ab0c2b8a2b430bed6bbb29b5036c33dbe4435
  name: harbor.poc.add2cloud.com/library/spring-petclinic
