apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:567b7a870897176b879573936c989eaa6310fa5cfb20a48fea3fbe47fc0d72e2
  name: harbor.poc.add2cloud.com/library/spring-petclinic
