apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- digest: sha256:13711c1fae3e4d3e84c3a1a72e7af8a587dbf8e62167daf47ebd4de6ac842f80
  name: harbor.poc.add2cloud.com/library/spring-petclinic
