apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: tbs-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: glenioborges/petclinic:b1.20201003.012824
        name: petclinic
        ports:
        - containerPort: 8080