apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  template:
    spec:
      containers:
      - name: spring-petclinic
        env:
        - name: ENVIRONMENT
          value: dev