apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

commonLabels:
  app: spring-petclinic
  revision: labelValue1
  sam: sam
resources:
- ../base
