apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

commonAnnotations:
  revision: sam

# commonLabels:
#   revision: sam
#   app: spring-petclinic
#   sam: sam

# images:
#   - name: spring-petclinic
#     newName: samarsinghal/spring-petclinic:latest
