apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

# patchesStrategicMerge:
# - ./deployment-patch.yaml

commonAnnotations:
  revision: sam
  revision-08184fcb8c72860d13a797eb1a81106e684eecc1: 08184fcb8c72860d13a797eb1a81106e684eecc1

namePrefix: dev-

# commonLabels:
#   revision: sam
#   app: spring-petclinic
#   sam: sam

# images:
#   - name: spring-petclinic
#     newName: samarsinghal/spring-petclinic:latest
